### ISSUE TITLE
Project offline, coophub.io domain due to expire in December 2024

### ISSUE THREAD

**Issue by chriscroome** [fiqus/coophub#150]
The `coophub.io` domain is registered until December:

```
whois coophub.io | grep Date
Updated Date: 2023-11-11T06:28:24Z
Creation Date: 2019-12-06T22:07:16Z
Registry Expiry Date: 2024-12-06T22:07:16Z
```

The site was [last online in 2022](https://web.archive.org/web/20220624055651/https://coophub.io/).

Has this project been abandoned?

**Comment by chriscroome** [comment]
There are later captures but they are [blank pages](https://web.archive.org/web/20240327121128/https://coophub.io/)... the last I found with content was 2022...

**Comment by pbrudnick** [comment]
It's fixed!
We had an issue with the certbot too

Thanks for taking care of it @chriscroome ❤️
