### ISSUE TITLE
Use an updated version of uglifyjs-webpack-plugin that don't break npm run deploy

### ISSUE THREAD

**Issue by diegomanuel** [fiqus/coophub#33]
After issue #22 and PR #32 the dep `uglifyjs-webpack-plugin` `v2.2.0` was downgraded to `v1.0.0-rc.0` because `v2` **breaks assets prod deploy** when running: `npm run deploy`.

The idea is to address this in the future, trying to keep all deps at its latests versions.

**Comment by mlambir** [comment]
done! removed github button and updated uglifyjs-webpack-plugin
