### ISSUE TITLE
Add gitlab API

### ISSUE THREAD

**Issue by pbrudnick** [fiqus/coophub#4]
Note that an org could have both github and gitlab.

- [x] We can specify if the coop user is from github **or/and** gitlab.
- [x] When get the repos for the cache get from gitlab api too
- [x] Show an icon in the repos box in the UI to distinguish between github/gitlab

**Comment by chriscroome** [comment]
We don't mirror our repos onto GitHub from https://git.coop/ (but perhaps we should one day...) so GitLab support would be welcome, we mostly have lots of [public Ansible roles](https://git.coop/webarch/) which are all works-in-progress...

**Comment by pbrudnick** [comment]
Added support for Gitlab in https://github.com/fiqus/coophub/pull/52
@chriscroome you are using a self-hosted Gitlab, and we are consuming the public gitlab.com API

**Comment by chriscroome** [comment]
Is it worth me opening an issue to request the adding of support for self hosted GitLab instances or would that be out of scope for this project?

**Comment by pbrudnick** [comment]
> Is it worth me opening an issue to request the adding of support for self hosted GitLab instances or would that be out of scope for this project?

could you provide access to your gitlab API? is it possible with self-hosted gitlab?

**Comment by pbrudnick** [comment]
I figured out that!
https://git.coop/api/v4/groups/
