### ISSUE TITLE
Support for git.coop

### ISSUE THREAD

**Issue by pbrudnick** [fiqus/coophub#53]
They are using a self-hosted Gitlab:
https://git.coop/api/v4/groups

See conversation in #4

**Comment by chriscroome** [comment]
Is there anything you would need from me to add [git.coop](https://git.coop/)?

**Comment by pbrudnick** [comment]
I guess no, I'll let you know :)

**Comment by pbrudnick** [comment]
btw, any idea or suggestion is welcome

**Comment by pbrudnick** [comment]
Merged support for git.coop!

@chriscroome **webarchitects** was added to: 
https://github.com/fiqus/coophub/blob/master/cooperatives.yml#L105-L111

Feel free to add more orgs from `git.coop`.

**Comment by chriscroome** [comment]
That's amazing, thanks @pbrudnick !

Now I have yet another reason to get all our Ansible code into a good enought state that it can go on Ansible Galaxy and also more reason to write better metadata for repos&hellip; :slightly_smiling_face: 

One thing I noticed is that while GitLab supports markdown in repo descriptions the [coophub.io](https://coophub.io/) site doesn't &mdash; I guess the easiest thing would be for me to make all the repo descriptions plain text?

Am I right in understanding that `login: <USERNAME_IN_THE_SOURCE>` is actually the GitLab group name, so in this case [webarch](https://git.coop/webarch)?

**Comment by pbrudnick** [comment]
> One thing I noticed is that while GitLab supports markdown in repo descriptions the coophub.io site doesn't — I guess the easiest thing would be for me to make all the repo descriptions plain text?

Yes, I'll create an issue for this.

> Am I right in understanding that login: <USERNAME_IN_THE_SOURCE> is actually the GitLab group name, so in this case webarch?

Exactly!
