### ISSUE TITLE
Can an organization that is part of the cooperative be added?

### ISSUE THREAD

**Issue by vitormattos** [fiqus/coophub#88]
We at @LibreCodeCoop have created and are maintaining a free-licensed digital signer, @LibreSign, can the LibreSign organization be added to CoopHub?

**Comment by pbrudnick** [comment]
Hey @vitormattos sorry about the delay, yes, if it is a co-op's org, its repos are considered co-op's repos.

**Comment by vitormattos** [comment]
@LibreSign is an organization created by @LibreCode to make repository management easier. The cooperative is @LibreCode.
